#!/usr/bin/env bash
# American English in project prose and comments.
#
# Not pedantry: the repository is public and read by judges, and mixed
# orthography reads as several people writing carelessly rather than one person
# writing deliberately.
#
# Vendored files are skipped — .claude/commands and .claude/skills are
# regenerated by `openspec update`, and package-lock.json contains real package
# names such as @img/colour.
set -uo pipefail
cd "$(git rev-parse --show-toplevel)"

# AnalyserNode is deliberately absent: it is the actual Web Audio API
# identifier, and "correcting" it would break the code.
WORDS=(honour behaviour initialis summaris catalogue defence colour favour
       centre travelling modelling labelled fulfil programme whilst amongst
       learnt spelt organis recognis normalis prioritis serialis utilis
       "\bgrey\b")

status=0
for word in "${WORDS[@]}"; do
  hits=$(git grep -Iin --untracked "$word" -- . \
           ':!*package-lock.json' ':!LICENSE' ':!.claude/commands' ':!.claude/skills' \
           ':!scripts/check-american-english.sh' 2>/dev/null || true)
  if [ -n "$hits" ]; then
    echo "British spelling ($word):"
    echo "$hits" | sed 's/^/  /'
    status=1
  fi
done

[ $status -eq 0 ] && echo "clean: American English throughout"
exit $status
